
version: "3.8"

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
      # Only build development stage from Dockerfile
      target: development
    # Mount our host dir to the docker container
    # Mount backend directory (./backend) to (:) docker container (/sophie/src/app)
    # Reflect File changes from host to container
    volumes:
      - ./backend:/sophie/src/app
      - /sophie/src/app/node_modules/
    # RUN in debug mode: npm run start:debug --> Also start your vscode debugger
    # Run in dev mode: npm run start:dev
    command: npm run start:debug
    depends_on: 
      - postgres
    environment:
      DATABASE_URL: postgres://user:admin@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - 3000:3000
      - 9229:9229
  
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
      target: development
    command: npm run start
    volumes:
      - ./frontend:/sophie/frontend/src/app
      - /sophie/frontend/src/app/node_modules
    ports:
      - 4200:4200
    links:
      - backend

  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    ports:
      - 35000:5432

  postgres_admin:
    image: dpage/pgadmin4:4.28
    depends_on: 
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
